version: '3.8'
networks:
  mynetwork:
    driver: bridge
services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - mynetwork



  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: video_transcriber_frontend_image
    environment:
      - REACT_APP_URL=http://django:8000/
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app/frontend/
    container_name: react_container_stream

